version: "3.9"
services:

  postgres:
    container_name: postgres
    image: postgres:15.2
    environment:
      POSTGRES_DB: "school"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "rootroot"
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data/:rw
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin  
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
